export const enum ContentType {
  PHONE = 'PHONE',

  EMAIL = 'EMAIL',

  ADDRESS = 'ADDRESS',

  INTRO = 'INTRO',

  IMG_HOME_BANNER = 'IMG_HOME_BANNER',
  IMG_CONTACT_BANNER = 'IMG_CONTACT_BANNER',
  IMG_ACHIEVEMENT_BANNER = 'IMG_ACHIEVEMENT_BANNER',
  IMG_LOGO = 'IMG_LOGO',
}
